// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed Oct 14 16:20:38 2020

binaryToBCD binaryToBCD_inst
(
	.number(number_sig) ,	// input [16:0] number_sig
	.digit0(digit0_sig) ,	// output [3:0] digit0_sig
	.digit1(digit1_sig) ,	// output [3:0] digit1_sig
	.digit2(digit2_sig) ,	// output [3:0] digit2_sig
	.digit3(digit3_sig) 	// output [3:0] digit3_sig
);

