// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Tue Oct 13 23:35:19 2020

display display_inst
(
	.sys_clk(sys_clk_sig) ,	// input  sys_clk_sig
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.digit0(digit0_sig) ,	// input [3:0] digit0_sig
	.digit1(digit1_sig) ,	// input [3:0] digit1_sig
	.digit2(digit2_sig) ,	// input [3:0] digit2_sig
	.digit3(digit3_sig) ,	// input [3:0] digit3_sig
	.digits(digits_sig) ,	// output [3:0] digits_sig
	.seg(seg_sig) 	// output [6:0] seg_sig
);

